apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipping-service-v81
  name: shipping-service-v81
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service-v81
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: shipping-service-v81
    spec:
      containers:
      - image: 195400145213.dkr.ecr.us-east-1.amazonaws.com/proyecto-ort-im:shipping-service-v81
        name: shipping-service-v81
        ports: 
        - containerPort: 80
          name: http
        volumeMounts:
        - name: persistent-storage
          mountPath: "/var/shipping-service-mnt"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pvc-efs
