apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service-product
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 80 
  selector:
    app: product-service-v30  

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service-payment
spec:
  type: LoadBalancer
  ports:
  - port: 80  
    targetPort: 80  
  selector:
    app: payment-service-v79  

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service-shipping
spec:
  type: LoadBalancer
  ports:
  - port: 80  
    targetPort: 80
  selector:
    app: shipping-service-v81  
